комарно
digitaldrugstech/prdx-bugtracker pull request #22
Opened 2024-08-27 19:12 UTC by TheMek0

Добавлен раздел для ошибок в дискорде(специально для меня, хихи), исправлены орфографические ошибки в названии шаблонов, а также в описании ошибки был сделан стиль текста: paragraph, а не short

2024-08-27 19:21 UTC, thehaffk approved these changes

2024-08-28 12:03 UTC, megazvezda reviewed
Слово "баги" не подходит и меняет смысл формы

2024-08-28 12:05 UTC, megazvezda requested changes
Нет

2024-08-28 12:06 UTC, megazvezda approved these changes
Приемлемо

2024-08-28 12:11 UTC, megazvezda approved these changes
Шаблон для воспроизведения хромает
Пойдет

2024-08-28 12:13 UTC, megazvezda requested changes
Нет

2024-08-28 12:13 UTC, megazvezda requested changes
Нет

2024-08-28 12:13 UTC, megazvezda requested changes
Нет

2024-08-28 12:13 UTC, megazvezda requested changes
Нет

2024-08-29 19:16 UTC, TheMek0 commented
ебать, я только сейчас понял, что это ответы идут на каждый коммит от самого последнего до самого первого

2024-09-03 20:08 UTC, closed without merging